config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
  get "flat/search", to: "flats#query"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord

  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, presence: true
  validates :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def query
    @flats = Flat.where("name LIKE '%#{params[:searchquery]}%'")
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to flats_path
    else
      render :edit
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :number_of_guests, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Update flat listing!" %>
<% end %>

app/views/flats/index.html.erb
<h1>Simple Airbnb</h1>

<h3><%= link_to "Create a flat listing!", new_flat_path %></h3>

<form action="/flat/search" method="get">
  <input type="text" name="searchquery" placeholder="Search for a flat">
  <input type="submit" value="search">
</form>

<br>

<% @flats.each do |flat| %>
  <h3> <%= flat.name %> </h3>
  <p> <%= flat.address %> </p>
  <p> <%= flat.description %> </p>
  <p> <%= flat.price_per_night %> </p>
  <p> <%= flat.number_of_guests %> </p>
  <%= link_to "More info", flat_path(flat) %>
  <br>
  <%= link_to "Edit", edit_flat_path(flat) %>
  <br>
  <%= link_to "Remove", flat_path(flat), method: :delete, data: { confirm: "Are you sure?" }  %>
  <hr>
<% end %>

app/views/flats/new.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Submit flat listing!" %>
<% end %>

app/views/flats/query.html.erb
<h3><%= link_to "Back to all listings", flats_path %></h3>

<% @flats.each do |flat| %>
  <h3> <%= flat.name %> </h3>
  <p> <%= flat.address %> </p>
  <p> <%= flat.description %> </p>
  <p> <%= flat.price_per_night %> </p>
  <p> <%= flat.number_of_guests %> </p>
  <hr>
<% end %>

app/views/flats/show.html.erb
  <h3> <%= @flat.name %> </h3>
  <p> <%= @flat.address %> </p>
  <p> <%= @flat.description %> </p>
  <p> <%= @flat.price_per_night %> </p>
  <p> <%= @flat.number_of_guests %> </p>
  <%= link_to "Back to listings", flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>